ModeloBundle\Entity\Departamento:
    type: entity
    table: departamento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador departamento'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombre departamento'
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Descripcion departamento'
    lifecycleCallbacks: {  }
