ModeloBundle\Entity\Equipo:
    type: entity
    table: equipo
    indexes:
        TCampeonato_idCampeonato:
            columns:
                - idCampeonato
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador Equipo'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombre Equipo'
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Descripcion equipo'
            column: Descripcion
    manyToOne:
        idcampeonato:
            targetEntity: Campeonato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCampeonato:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
