ModeloBundle\Entity\Partido:
    type: entity
    table: partido
    indexes:
        Tcampeonato_idcampeonato:
            columns:
                - idcampeonato
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador Partido'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: false
            options:
                comment: 'Fecha y Hora del Partido'
    manyToOne:
        idcampeonato:
            targetEntity: Campeonato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcampeonato:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
