ModeloBundle\Entity\Tiposocio:
    type: entity
    table: tiposocio
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Identificador Tipo Socio'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Nombre del tipo de socio'
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'descripcion del tipo de socio'
    lifecycleCallbacks: {  }
